package com.alexbomber12.memtag.ui.theme

import androidx.compose.ui.graphics.Color

val SuccessGreen = Color(0xFF2FBF71)
val SignalOrange = Color(0xFFF08A3C)
val SignalYellow = Color(0xFFF4D44E)

val LightPrimary = Color(0xFF58A4EC)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD7ECFF)
val LightOnPrimaryContainer = Color(0xFF103C63)
val LightSecondary = Color(0xFF5F6B7A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE6EBF1)
val LightOnSecondaryContainer = Color(0xFF1A2430)
val LightTertiary = Color(0xFFF08A3C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFE2CC)
val LightOnTertiaryContainer = Color(0xFF4A2C15)
val LightBackground = Color(0xFFF5F7FA)
val LightOnBackground = Color(0xFF1B1C1E)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1B1C1E)
val LightSurfaceVariant = Color(0xFFEFF2F5)
val LightOnSurfaceVariant = Color(0xFF606773)
val LightOutline = Color(0xFFD6DCE3)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)

val DarkPrimary = Color(0xFF8CC2F3)
val DarkOnPrimary = Color(0xFF0C2A44)
val DarkPrimaryContainer = Color(0xFF1E4F7A)
val DarkOnPrimaryContainer = Color(0xFFD7ECFF)
val DarkSecondary = Color(0xFFB7C0CA)
val DarkOnSecondary = Color(0xFF25303A)
val DarkSecondaryContainer = Color(0xFF3B4651)
val DarkOnSecondaryContainer = Color(0xFFDDE3EA)
val DarkTertiary = Color(0xFFFFB77C)
val DarkOnTertiary = Color(0xFF4A2C15)
val DarkTertiaryContainer = Color(0xFF6A3E1E)
val DarkOnTertiaryContainer = Color(0xFFFFE2CC)
val DarkBackground = Color(0xFF101317)
val DarkOnBackground = Color(0xFFE0E4EA)
val DarkSurface = Color(0xFF161A1E)
val DarkOnSurface = Color(0xFFE0E4EA)
val DarkSurfaceVariant = Color(0xFF3A4047)
val DarkOnSurfaceVariant = Color(0xFFC0C6CF)
val DarkOutline = Color(0xFF8B929B)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
